version: '20.10'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : 123
      POSTGRES_DB : nest
    networks:
      - AbhiramGatreddi
      
  test-db:
    image: postgres:13
    ports:
      - 5445:5432
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : 123
      POSTGRES_DB : nest
    networks:
      - AbhiramGatreddi
networks:
  AbhiramGatreddi:
    